### ISSUE TITLE
[UI/UX]  Implement front end for chatpilot

### ISSUE THREAD

**Issue by leocodeio** [leocodeio/chatpilot#10]
step1 - **At root folder (/chatpilot)  - create a folder named bot which will be in react -**
hint - **In terminal go to root folder and npx create-react-app bot**

step2 - **Find a template that matches our needs** (optinal -- use already available components )
hint - **flowbite or shadccn**

![image](https://github.com/user-attachments/assets/0e865f80-f783-43be-865e-ffdaba5179d6)

**Comment by likhita-maddala** [comment]
assigned to me
